### ISSUE TITLE
no matching function for call to

### ISSUE THREAD

**Issue by HOSTEER** [Ralim/STM32-USB-PD-Demo#2]
Hello,

I'm trying to compile the project and I get this error in the "Problems" window when compiling in STM32CubeIDE

`no matching function for call to 'PolicyEngine::PolicyEngine(FUSB302&, uint32_t (&)(), void (&)(uint32_t), void (&)(pd_msg*, bool), bool (&)(const pd_msg*, pd_msg*))'`

I did open the project in CubeIDE without migrating it  and add the submodule for usb-pd libraries.

Do you have a clue or some tips to solve this issue ?

**Comment by Ralim** [comment]
Hia,
Did you use a git recursive checkout?
The demo uses git submodule (as you can [see here](https://github.com/Ralim/STM32-USB-PD-Demo/tree/main/Workspace/USBPDDemo/Core/Drivers)).

This likely means that you have used a newer version of the usb-pd library which has been updated since this demo was made.


The [newer version of that function](https://github.com/Ralim/usb-pd/blob/609dda7d16a5d572b87794f4fd3b3c01f1bfd1f8/include/policy_engine.h#L45) has been extended to have new arguments for EPR support, so you will need to provide the new arguments.

**Comment by HOSTEER** [comment]
Thank a lot ! That's it. I'm not familiar with submodule and I did not check that the submodule commit was right.
